### ISSUE TITLE
Reminder for tasks containing due time

### ISSUE THREAD

**Issue by soywod** [soywod/unfog#41]
The simplest way could be to prepend any output with incoming tasks. Otherwise we need a kind of a service that runs in background and checks whenever a task is coming. I have no idea how to do this in Haskell, I will search a bit. Propositions are welcomed.

**Comment by kristijanhusak** [comment]
In case of a background task, how you plan to notify the user? Via native notifications (for example, notify-send on linux), or something else?
I had an idea to do it in Vim, but I don't think there is a way to communicate something from any task outside to Vim. Maybe only neovim, since it allows attaching, but I'm also not sure about that.

**Comment by soywod** [comment]
After thinking for a while, this feature seems out of the scope of the tool. There is also too many different configurations, how to notify properly for all cases? Which kind of service system to use? etc. A better approach IMO is to add example in the README on how to set up such service depending on the user configuration (OS, type of service), or maybe to provide an bash script (like the completion). What do you think?

**Comment by kristijanhusak** [comment]
I'm still convinced this could be done fairly simple in vim/neovim with timers feature. It will not be so precise, but having a timer check the state of the tasks and printing them out in some way would do the trick.
This could be an additional plugin alongside unfog.vim that would do this. It would be helpful if unfog would expose a call that returns only tasks that happen in specified number of minutes. For example, if i do `unfog list --reminder-time=10`, it will return all tasks that are due to in ~10 min. Then vim can have a configuration like `let g:unfog_reminders = [5, 10]`, and every minute, timer would check if ther are any tasks that happen in those minutes, and print them out.

**Comment by soywod** [comment]
Vim or Neovim are not the right place for such a timer. Just because once you exit them, your timer is down. The call exposure is a good idea, but I think it should be called outside of the tool itself.

> This could be an additional plugin alongside unfog.vim

In fact a binding could be enough in the Vim/Neovim config file. I will think about it.

**Comment by soywod** [comment]
Here the idea I have in mind:

- Add a new command `due-dates:watch` that spawns a daemon
- The daemon checks every minutes if there is a task with a coming due date
- When a due date matches, it executes one or more commands
- Commands can be customized in the config file `~/.config/unfog/config.toml` (needs unfog v1.0.2+)
- This way, Vim just open a socket to this new command

I would like your opinion about this draft, let me know ;)

**Comment by kristijanhusak** [comment]
That sounds nice. It allows using it outside of vim if needed, so it has much better flexibility.

**Comment by soywod** [comment]
I decided to go for a simpler version for now. I added an option to the list query `--due-in MINS` that takes an integer (the number of minutes) and filters tasks with a due date inferior than MINS. This way any outside script can be called every minutes to check tasks with due time. It will come with the next release (it's already merged on master).
