### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by razcore-rad** [soywod/unfog#52]
Do you know why I'd get this error?

```sh
~ 
❯ unfog upgrade                                                                                                                                                       09:43:32
bash: line 1: 404:: command not found
```

I looked at the call and it's super simple. If I run it manually it works just fine.

```sh
~ 
❯ curl -sSL https://raw.githubusercontent.com/soywod/unfog/master/install.sh | bash                                                                                   09:41:16
Downloading latest linux release...
Installing binaries...
Installing bash completion...
Unfog v1.0.3 installed!
```

**Comment by soywod** [comment]
From which version did you try to upgrade? It looks like the link returned a 404. It could be the link which changed, or just GitHub was unavailable for a while. The `upgrade` works fine for me, I cannot reproduce.

**Comment by razcore-art** [comment]
So I just tried this now.

```sh
~ 
❯ unfog version                                                                                                                                                       12:01:32
1.0.3

~ 
❯ unfog upgrade                                                                                                                                                       12:01:37
bash: line 1: 404:: command not found
```
It isn't a problem with the Github service or the net. Now that I think about it, I suspect it may have to do with environment variables or something like that, but I'm not sure.

**Comment by soywod** [comment]
It is really strange. I do not understand what is happening. For now I cannot reproduce, I leave the issue open if someone else encounter the same problem. I will try to dig a bit more and let you know.

**Comment by razcore-art** [comment]
No worries, thanks

**Comment by templeman** [comment]
I ran into this as well:

```
$ unfog version
1.0.3

$ unfog upgrade
bash: line 1: 404:: command not found
```
Running `macOS 10.14.6`

It seems like this might be due to a simple version mismatch. Looking at the repo, there was a change to the upgrade paths _after_ the last release. For example, my local unfog binary file is from 2020-12-05, but there was a [path change](https://github.com/soywod/unfog/commit/0c9754070402bf14d183fd86ed36efbb3fc408c7#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fL7) committed to the repo on 2020-12-17. I'm guessing the 1.0.3 binary is still pointing to the old upgrade path with `osx` instead of the new `macos` identifier.

**Comment by soywod** [comment]
It's what I thought, but how to explain it still does not work after reinstalling the version using cURL?

**Comment by templeman** [comment]
When I remove unfog and install fresh using cURL: 
`curl -sSL https://raw.githubusercontent.com/soywod/unfog/master/install.sh | bash`
I still end up with v1.0.3, since that is the latest release on master. And that release doesn't yet have the updated paths, so the `upgrade` command is still broken. So, maybe a new tagged release would fix it for those installing for the first time? Anyone that previously installed would probably have to reinstall manually for the `unfog upgrade` command to work, however.

**Comment by soywod** [comment]
I just released the [`v1.0.4`](https://github.com/soywod/unfog/releases/tag/v1.0.4) and the issue seemed to be fixed. Do you confirm?

**Comment by razcore-rad** [comment]
Yes, I confirm it now works. I guess the environment vars were the culprit, hm? :)

**Comment by soywod** [comment]
Exactly :smiley: thanks for your help!

**Comment by razcore-rad** [comment]
Always happy to point out errors! c:
